name: Sophie French
favicon: null
layout_spectrum: 0.7521198557224125
typography_spectrum: 0.4754132116213441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24565426190383732
  lightness: 0.9177620785776526
  saturation: 0.20792404329404235
  rhythmicContrast: 0.5097075290977955
purpose: []
