name: Sophie French
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80102
title: Sophie French - Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.9375
  rhythmicContrast: 0.5097075290977955
purpose: []
